language: swift
os: osx
osx_image: xcode11.3
before_script:
  - gem install xcpretty
script:
  - swift package generate-xcodeproj
  - set -o pipefail && xcodebuild -scheme Swish clean build test | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash)